#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Apr 21 11:43:44 EDT 2022
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib axi_infrastructure_v1_1_0 axi_vip_v1_1_11 processing_system7_vip_v1_0_13 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 fifo_generator_v13_2_6 axis_infrastructure_v1_1_0 axis_data_fifo_v2_0_7 lib_pkg_v1_0_2 lib_fifo_v1_0_15 blk_mem_gen_v8_4_5 lib_bmg_v1_0_14 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_27 axi_vdma_v6_3_13 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_25 axi_data_fifo_v2_1_24 axi_crossbar_v2_1_26 axi_lite_ipif_v3_0_4 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_13 v_tc_v6_2_3 xlconcat_v2_1_4 interrupt_control_v3_1_4 axi_gpio_v2_0_27 xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_17 floating_point_v7_0_19 xbip_dsp48_mult_v3_0_6 xbip_dsp48_multadd_v3_0_6 div_gen_v5_1_18 axi_protocol_converter_v2_1_25)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2021.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "/opt/xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/xilinx/Vivado/2021.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/xilinx/Vivado/2021.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/xilinx/Vivado/2021.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "/opt/xilinx/Vivado/2021.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/xilinx/Vivado/2021.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/xilinx/Vivado/2021.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/xilinx/Vivado/2021.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ipshared/40b8/hdl/LineBuffer.vhd" \
    "$ref_dir/../../../bd/system/ipshared/40b8/hdl/AXI_BayerToRGB.vhd" \
    "$ref_dir/../../../bd/system/ip/system_AXI_BayerToRGB_1_0/sim/system_AXI_BayerToRGB_1_0.vhd" \
    "$ref_dir/../../../bd/system/ipshared/30c9/hdl/StoredGammaCoefs.vhd" \
    "$ref_dir/../../../bd/system/ipshared/30c9/hdl/AXI_GammaCorrection.vhd" \
    "$ref_dir/../../../bd/system/ip/system_AXI_GammaCorrection_0_0/sim/system_AXI_GammaCorrection_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_DVIClocking_0_0/sim/system_DVIClocking_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_11 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/63b7/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_processing_system7_0_0/sim/system_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/d57c/src/ClockGen.vhd" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/d57c/src/SyncAsync.vhd" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/d57c/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/d57c/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/d57c/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/d57c/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/d57c/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rgb2dvi_0_0/sim/system_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_rst_clk_wiz_0_50M_0/sim/system_rst_clk_wiz_0_50M_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rst_vid_clk_dyn_0/sim/system_rst_vid_clk_dyn_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_6 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/sim/cdc_fifo.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/sim/ila_rxclk.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/sim/ila_rxclk_lane.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/sim/ila_vidclk.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/sim/line_buffer.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ipshared/7681/hdl/CRC16_behavioral.vhd" \
    "$ref_dir/../../../bd/system/ipshared/7681/hdl/DebugLib.vhd" \
    "$ref_dir/../../../bd/system/ipshared/7681/hdl/ECC.vhd" \
    "$ref_dir/../../../bd/system/ipshared/7681/hdl/SyncAsync.vhd" \
    "$ref_dir/../../../bd/system/ipshared/7681/hdl/SyncAsyncReset.vhd" \
    "$ref_dir/../../../bd/system/ipshared/7681/hdl/LLP.vhd" \
    "$ref_dir/../../../bd/system/ipshared/7681/hdl/SimpleFIFO.vhd" \
    "$ref_dir/../../../bd/system/ipshared/7681/hdl/LM.vhd" \
    "$ref_dir/../../../bd/system/ipshared/7681/hdl/MIPI_CSI2_Rx.vhd" \
    "$ref_dir/../../../bd/system/ipshared/7681/hdl/MIPI_CSI_2_RX_v1_0_S_AXI_LITE.vhd" \
    "$ref_dir/../../../bd/system/ipshared/7681/hdl/MIPI_CSI2_RxTop.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/sim/system_MIPI_CSI_2_RX_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/sim/ila_sfen_rxclk.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/sim/ila_sfen_refclk.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/sim/ila_scnn_refclk.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/DPHY_Pkg.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/DebugLib.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/HS_Deserializer.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/GlitchFilter.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/HS_Clocking.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/InputBuffer.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/DPHY_LaneSFEN.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/DPHY_LaneSCNN.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/S_AXI_Lite.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/MIPI_DPHY_Receiver.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/sim/system_MIPI_D_PHY_RX_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_15 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/a4ed/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3a3e/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_27 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/9b19/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_13 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_vdma_0_0/sim/system_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/e1e6/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_24 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/fa53/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ac57/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/da0d/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_v_axi4s_vid_out_0_0/sim/system_v_axi4s_vid_out_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_mmcm_pll_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_ipif_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_family_support.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_family.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_soft_reset.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_pselect_f.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_video_dynclk_0_address_decoder.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_video_dynclk_0_slave_attachment.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_video_dynclk_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_clk_wiz_drp.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_axi_clk_config.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_tc_v6_2_3 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ee1d/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_vtg_0/sim/system_vtg_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconcat_0_0/sim/system_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_27 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/a5bb/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_0_0/sim/system_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/system/ipshared/6d47/src/clkdiv.vhd" \
    "$ref_dir/../../../bd/system/ipshared/6d47/src/motor_ctrl.vhd" \
    "$ref_dir/../../../bd/system/ipshared/6d47/src/motor_pwm.vhd" \
    "$ref_dir/../../../bd/system/ipshared/6d47/hdl/motor_steer_ctrl_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/system/ipshared/6d47/src/motorsteerctrl.vhd" \
    "$ref_dir/../../../bd/system/ipshared/6d47/src/steer_controller.vhd" \
    "$ref_dir/../../../bd/system/ipshared/6d47/src/steer_ctrl.vhd" \
    "$ref_dir/../../../bd/system/ipshared/6d47/hdl/motor_steer_ctrl_v1_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_motor_steer_ctrl_0_1/sim/system_motor_steer_ctrl_0_1.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_1_0/sim/system_axi_gpio_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_videoprocessor_0_0/src/div_gen_0_3/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_videoprocessor_0_0/src/div_gen_0_3/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_videoprocessor_0_0/src/div_gen_0_3/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_videoprocessor_0_0/src/div_gen_0_3/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_videoprocessor_0_0/src/div_gen_0_3/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_videoprocessor_0_0/src/div_gen_0_3/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_17 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_videoprocessor_0_0/src/div_gen_0_3/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_0_19 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_videoprocessor_0_0/src/div_gen_0_3/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_mult_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_videoprocessor_0_0/src/div_gen_0_3/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_videoprocessor_0_0/src/div_gen_0_3/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work div_gen_v5_1_18 $vhdlan_opts \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_videoprocessor_0_0/src/div_gen_0_3/hdl/div_gen_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_videoprocessor_0_0/src/div_gen_0_3/sim/div_gen_0.vhd" \
    "$ref_dir/../../../bd/system/ipshared/06e1/hdl/videoprocessor_v2_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/system/ipshared/06e1/hdl/videoprocessor_v2_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_videoprocessor_0_0/sim/system_videoprocessor_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/8fe4/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/36fa/hdl" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ipshared/62b6" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../Zybo-Z7-20-pcam-5c.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_1/sim/system_auto_pc_1.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_2/sim/system_auto_pc_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/sim/system.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/mike/Desktop/ProjectVersions/projectsave0/Zybo-Z7-20-pcam-5c-2019.1/vivado_proj/Zybo-Z7-20-pcam-5c.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
